###
 curl http://localhost:8080/book --include --header "Content-Type: application/json"\
 --request "POST"\
 --data '{"id": "","name": "Spring in Action","price": 99.66,"author": "Craig Walls"}'


'{"id": "","name": "Spring in Action","price": 99.66,"author": "Craig Walls"}'
POST http://localhost:8080/albums
Content-Type: application/json

{
  "id": "4",
  "title": "The Modern Sound of Betty Carter",
  "artist": "Betty Carter",
  "price": 49.99
}

###



### add
POST http://localhost:8080/books
Content-Type: application/json

{"name": "core JAVA", "price": 16.99, "author": "Gary Cornell"}

### getList
GET http://localhost:8080/books/ff00ca2c-5ac9-4ecc-9d8a-a22c8f1b0be5
Content-Type: application/json

### update
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "price": 200
}

### delete
DELETE localhost:8080/books/1
Content-Type: application/json