###
 curl http://localhost:8080/book --include --header "Content-Type: application/json"\
 --request "POST"\
 --data '{"id": "","name": "Spring in Action","price": 99.66,"author": "Craig Walls"}'


'{"id": "","name": "Spring in Action","price": 99.66,"author": "Craig Walls"}'
POST http://localhost:8080/albums
Content-Type: application/json

{
  "id": "4",
  "title": "The Modern Sound of Betty Carter",
  "artist": "Betty Carter",
  "price": 49.99
}

###



### add
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{"name": "Spring in Actionlvjnelvenvlrjvblvnksdnfsldkjvnlvnewlviewbvleivjbewlvewbvewverfvrwfvrwvv", "price": 1.00, "author": "Craig Walls"}

### getList
GET http://localhost:8080/api/v1/books/2
Content-Type: application/json

### update
PATCH http://localhost:8080/api/v1/books/6
Content-Type: application/json

{
  "name": "Spring in",
  "price": 200
}

### delete
DELETE localhost:8080/api/v1/books/20
Content-Type: application/json